/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atleticaRanasgallaAbenante;

/**
 *
 * @author abenante.lucia
 */
public class GraficaGara extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraficaGara.class.getName());
    private Meeting meeting;
    private Atleta atletaCorrente;
    private Gara garaCorrente;
    /**
     * Creates new form GraficaGara
     */
    public GraficaGara(Meeting meeting, Atleta atleta) {
        initComponents();
        this.meeting = meeting;
        this.atletaCorrente = atleta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        cobTipoGara = new javax.swing.JComboBox<>();
        cobSpecialita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGraduatoria = new javax.swing.JTextArea();
        lblSelezione = new javax.swing.JLabel();
        btnMostraGraduatorie = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione Gara");
        setResizable(false);

        cobTipoGara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corsa", "Lancio", "Salto" }));
        cobTipoGara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobTipoGaraActionPerformed(evt);
            }
        });

        cobSpecialita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100 metri", "200 metri", "400 metri", "Salto in alto", "Salto in lungo", "Giavellotto", "Peso", "Disco" }));
        cobSpecialita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobSpecialitaActionPerformed(evt);
            }
        });

        btnAvvia.setBackground(new java.awt.Color(30, 100, 200));
        btnAvvia.setForeground(new java.awt.Color(255, 255, 255));
        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tipo di gara");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Specialità");

        txaGraduatoria.setEditable(false);
        txaGraduatoria.setBackground(new java.awt.Color(255, 255, 255));
        txaGraduatoria.setColumns(20);
        txaGraduatoria.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaGraduatoria.setRows(5);
        txaGraduatoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Graduatoria"));
        jScrollPane1.setViewportView(txaGraduatoria);

        lblSelezione.setBackground(new java.awt.Color(240, 240, 245));
        lblSelezione.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblSelezione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelezione.setText("Seleziona la gara");

        btnMostraGraduatorie.setBackground(new java.awt.Color(204, 102, 0));
        btnMostraGraduatorie.setForeground(new java.awt.Color(255, 255, 255));
        btnMostraGraduatorie.setText("Mostra Graduatorie");
        btnMostraGraduatorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraGraduatorieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cobTipoGara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(cobSpecialita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAvvia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(lblSelezione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostraGraduatorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblSelezione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobTipoGara)
                    .addComponent(cobSpecialita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvvia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostraGraduatorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        // TODO add your handling code here:
        // if combobox2.text== 100...200...400 passi il range per il rnd che serve per la prestazione
        //(44, 60) 400, (10, 22) 200, (9, 13)100
        //(180, 200)Alto, (100, 170) Lungo
        //(100, 125) giavellotto, (150, 190) peso, (60, 75) disco
        String tipo = (String) cobTipoGara.getSelectedItem();
        String specialita = (String) cobSpecialita.getSelectedItem();
        int r1, r2;

        switch (specialita) {
            case "100 metri":
                r1 = 9;
                r2 = 13;
                break;
            case "200 metri":
                r1 = 10;
                r2 = 22;
                break;
            case "400 metri":
                r1 = 44;
                r2 = 60;
                break;
            case "Salto in alto":
                r1 = 180;
                r2 = 200;
                break;
            case "Salto in lungo":
                r1 = 100;
                r2 = 170;
                break;
            case "Giavellotto":
                r1 = 100;
                r2 = 125;
                break;
            case "Peso":
                r1 = 150;
                r2 = 190;
                break;
            case "Disco":
                r1 = 60;
                r2 = 75;
                break;
            default:
                r1 = 9;
                r2 = 13;
                break;
        }

        // cerca se la gara esiste già nel meeting, altrimenti la crea
        Gara garaCorrente = null;
        for (Gara g : meeting.getGare()) {
            if (g.getNome().equals(specialita)) {
                garaCorrente = g;
                break;
            }
        }
        if (garaCorrente == null) {
            switch (tipo) {
                case "Corsa":
                    garaCorrente = new GaraCorsa(new java.util.ArrayList<>(), specialita, r1, r2);
                    break;
                case "Lancio":
                    garaCorrente = new GaraLancio(new java.util.ArrayList<>(), specialita, r1, r2);
                    break;
                case "Salto":
                    garaCorrente = new GaraSalto(new java.util.ArrayList<>(), specialita, r1, r2);
                    break;
            }
            meeting.aggiungiGara(garaCorrente);
        }

        garaCorrente.iscrizione(atletaCorrente);

        // torna alla form atleta
        GraficaAtleta atleta = new GraficaAtleta(meeting);
        atleta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void cobSpecialitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobSpecialitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobSpecialitaActionPerformed

    private void cobTipoGaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobTipoGaraActionPerformed
        // TODO add your handling code here:
        String tipo = (String) cobTipoGara.getSelectedItem();
        cobSpecialita.removeAllItems();

        switch (tipo) {
            case "Corsa":
                cobSpecialita.addItem("100 metri");
                cobSpecialita.addItem("200 metri");
                cobSpecialita.addItem("400 metri");
                break;
            case "Salto":
                cobSpecialita.addItem("Salto in alto");
                cobSpecialita.addItem("Salto in lungo");
                break;
            case "Lancio":
                cobSpecialita.addItem("Giavellotto");
                cobSpecialita.addItem("Peso");
                cobSpecialita.addItem("Disco");
                break;
        }
    }//GEN-LAST:event_cobTipoGaraActionPerformed

    private void btnMostraGraduatorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraGraduatorieActionPerformed
        // TODO add your handling code here:
        String testo = "";
        for (Gara g : meeting.getGare()) {
            testo += g.graduatoria() + "\n";
        }
        txaGraduatoria.setText(testo);
    }//GEN-LAST:event_btnMostraGraduatorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraficaGara(new Meeting(new java.util.ArrayList<>()), new Atleta("", 0, "", 0)).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnMostraGraduatorie;
    private javax.swing.JComboBox<String> cobSpecialita;
    private javax.swing.JComboBox<String> cobTipoGara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelezione;
    private javax.swing.JTextArea txaGraduatoria;
    // End of variables declaration//GEN-END:variables
}
